2024-09-14 13:06:22 - api.task_service - INFO - Retrieved 10 created tasks for user 1
2024-09-14 13:49:23 - api.auth_impl - INFO - Authentication successful for user: nihiyauj@gmail.com
2024-09-14 13:51:15 - api.auth_impl - INFO - Authentication successful for user: nihindu.20222156@iit.ac.lk
2024-09-14 13:51:45 - api.task_service - INFO - Retrieved 1 created tasks for user 2
2024-09-14 13:53:10 - api.task_service - ERROR - Unexpected error updating task with ID 5: 404: Task with ID 5 not found
2024-09-14 13:53:32 - api.task_service - ERROR - Unexpected error updating task with ID 5: 404: Task with ID 5 not found
2024-09-14 13:53:51 - api.task_service - ERROR - Unexpected error updating task with ID 5: 404: Task with ID 5 not found
2024-09-14 13:54:21 - api.task_service - ERROR - Unexpected error updating task with ID 6: TaskActivityImpl.log_task_history() got multiple values for argument 'task_id'
2024-09-14 13:55:02 - api.task_service - ERROR - Unexpected error updating task with ID 6: TaskActivityImpl.log_task_history() got multiple values for argument 'task_id'
2024-09-14 13:57:49 - api.task_service - ERROR - Unexpected error updating task with ID 6: TaskActivityImpl.log_task_history() got multiple values for argument 'task_id'
2024-09-14 14:02:46 - api.task_service - INFO - Task with ID 6 updated successfully
2024-09-14 14:04:49 - api.task_service - INFO - Task with ID 12 updated successfully
2024-09-14 14:05:47 - api.task_service - INFO - Task with ID 12 updated successfully
2024-09-14 14:06:37 - api.task_service - INFO - Email sent successfully
2024-09-14 14:06:37 - api.task_service - INFO - Task with ID 12 updated successfully
